//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrowdfundingPlan
    {
        public string ID { get; set; }
        public string ShortAlias { get; set; }
        public string CrowdfundingPlan1 { get; set; }
        public string CrowdfundingAmount { get; set; }
        public string Percentage { get; set; }
        public string Prerelease { get; set; }
        public string BegingDate { get; set; }
        public string EndDate { get; set; }
        public string SubmitDate { get; set; }
    }
}
