//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrowdfundingSolutionEntities : DbContext
    {
        public CrowdfundingSolutionEntities()
            : base("name=CrowdfundingSolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Album { get; set; }
        public DbSet<Attachment> Attachment { get; set; }
        public DbSet<Basic> Basic { get; set; }
        public DbSet<Contact> Contact { get; set; }
        public DbSet<CrowdfundingPlan> CrowdfundingPlan { get; set; }
        public DbSet<Detailed> Detailed { get; set; }
        public DbSet<ProjectManage> ProjectManage { get; set; }
    }
}
