//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailed
    {
        public string ID { get; set; }
        public string BasicID { get; set; }
        public string ProjectDetail { get; set; }
        public string MarketAnalysis { get; set; }
        public string EarningsForecast { get; set; }
        public string RiskControl { get; set; }
        public string DevelopmentPlan { get; set; }
        public string CoreCompetition { get; set; }
        public string SubmitDate { get; set; }
    }
}
