//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MulticluehnSolution.Web.WcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/TestGetData", ReplyAction="http://tempuri.org/ICrowdfundingPlan/TestGetDataResponse")]
        string TestGetData(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/TestGetData", ReplyAction="http://tempuri.org/ICrowdfundingPlan/TestGetDataResponse")]
        System.Threading.Tasks.Task<string> TestGetDataAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetByID", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetByIDResponse")]
        string CrowdfundingPlanGetByID(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetByID", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetByIDResponse")]
        System.Threading.Tasks.Task<string> CrowdfundingPlanGetByIDAsync(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanUpdate", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanUpdateResponse")]
        void CrowdfundingPlanUpdate(string Crowdmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanUpdate", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanUpdateResponse")]
        System.Threading.Tasks.Task CrowdfundingPlanUpdateAsync(string Crowdmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanAdd", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanAddResponse")]
        void CrowdfundingPlanAdd(string Crowdmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanAdd", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanAddResponse")]
        System.Threading.Tasks.Task CrowdfundingPlanAddAsync(string Crowdmodel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetAll", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetAllResponse")]
        string CrowdfundingPlanGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetAll", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanGetAllResponse")]
        System.Threading.Tasks.Task<string> CrowdfundingPlanGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanDelete", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanDeleteResponse")]
        void CrowdfundingPlanDelete(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanDelete", ReplyAction="http://tempuri.org/ICrowdfundingPlan/CrowdfundingPlanDeleteResponse")]
        System.Threading.Tasks.Task CrowdfundingPlanDeleteAsync(string ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MulticluehnSolution.Web.WcfService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MulticluehnSolution.Web.WcfService.IService>, MulticluehnSolution.Web.WcfService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestGetData(string str) {
            return base.Channel.TestGetData(str);
        }
        
        public System.Threading.Tasks.Task<string> TestGetDataAsync(string str) {
            return base.Channel.TestGetDataAsync(str);
        }
        
        public string CrowdfundingPlanGetByID(string ID) {
            return base.Channel.CrowdfundingPlanGetByID(ID);
        }
        
        public System.Threading.Tasks.Task<string> CrowdfundingPlanGetByIDAsync(string ID) {
            return base.Channel.CrowdfundingPlanGetByIDAsync(ID);
        }
        
        public void CrowdfundingPlanUpdate(string Crowdmodel) {
            base.Channel.CrowdfundingPlanUpdate(Crowdmodel);
        }
        
        public System.Threading.Tasks.Task CrowdfundingPlanUpdateAsync(string Crowdmodel) {
            return base.Channel.CrowdfundingPlanUpdateAsync(Crowdmodel);
        }
        
        public void CrowdfundingPlanAdd(string Crowdmodel) {
            base.Channel.CrowdfundingPlanAdd(Crowdmodel);
        }
        
        public System.Threading.Tasks.Task CrowdfundingPlanAddAsync(string Crowdmodel) {
            return base.Channel.CrowdfundingPlanAddAsync(Crowdmodel);
        }
        
        public string CrowdfundingPlanGetAll() {
            return base.Channel.CrowdfundingPlanGetAll();
        }
        
        public System.Threading.Tasks.Task<string> CrowdfundingPlanGetAllAsync() {
            return base.Channel.CrowdfundingPlanGetAllAsync();
        }
        
        public void CrowdfundingPlanDelete(string ID) {
            base.Channel.CrowdfundingPlanDelete(ID);
        }
        
        public System.Threading.Tasks.Task CrowdfundingPlanDeleteAsync(string ID) {
            return base.Channel.CrowdfundingPlanDeleteAsync(ID);
        }
    }
}
