//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic
    {
        public string ID { get; set; }
        public string ProjectName { get; set; }
        public string Synopsis { get; set; }
        public string IndustryID { get; set; }
        public string AreaID { get; set; }
        public string Highlight { get; set; }
        public string Promoter { get; set; }
        public string Website { get; set; }
        public string BusinessProgress { get; set; }
        public string BaseCity { get; set; }
        public string FoundingTime { get; set; }
        public string Tags { get; set; }
        public string Stage { get; set; }
        public string IsHaveOther { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ShareholderCount { get; set; }
        public string EmployeesCount { get; set; }
        public string ProjectDate { get; set; }
        public string SubmitDate { get; set; }
    }
}
